name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate --no-interaction
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  ssh-deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests
    environment:
      name: production
      url: https://central.hydephp.com
    steps:
      - name: Connect to SSH
        uses: matheusvanzan/sshpass-action@bcfb79c75dc1ec6631d3b7a8296c2f26f9f3bac9
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASS }}
          run: |
            cd $SSH_PATH
            bash update.sh

      - name: Check website status
        uses: pavelsaman/website-check@330f28d895a5c786f8d0bbfd1a3ccb15bfe1fc3e
        with:
          url: https://central.hydephp.com
          status_code: 200
